# https://taskfile.dev

version: '3.37'

interval: '100ms'

vars:

tasks:
  default:
    desc: "Lint check and unit test"
    deps: [flake8, test]

  watch:
    desc: "Watch flake8 and unit tests"
    deps: [flake8, test]
    watch: true
    sources:
      - '**/*.py'
      - '*.yml'

  flake8:
    aliases: [lint]
    desc: "Lint check"
    watch: true
    cmds:
      - flake8

  test:
    desc: "Unit tests"
    watch: true
    cmds:
      - pytest

  kick:
    desc: Kick the CICD pipeline.
    vars:
      KICK: "$(pwd)/.kick-pipeline"
    cmds:
      - |
        date > {{.KICK}}
        git add {{.KICK}}
        git ci -m "kick"
        git push